app.endpoints: https://checkimages.payments.intuit.net/T360_CheckImage/v2/checkimages/health,
               https://checkimages.payments.intuit.net/T360_CheckImage/v2/signatureimages/health,
               https://cdm.ihub.payments.intuit.com/MMDS_CDMService/v2/authorizations/health,
               https://cdm.ihub.payments.intuit.com/MMDS_CDMService/v2/transactions/health,
               https://cdm.ihub.payments.intuit.com/MMDS_CDMService/v2/mobilesignatures/health,
               https://cdm.ihub.payments.intuit.com/MMDS_CDMService/v2/batch/health,
               https://cdm.ihub.payments.intuit.com/Merchant-Report/v2/merchantdashboard/health,
               https://txnv4services.payments.intuit.net/health,
               https://lookup.ihub.payments.intuit.com/v2/health,
               https://txndisposition.payments.intuit.net/T360_TxnDisposition/v2/txnlifecycle/health



logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.client: DEBUG
    com.intuit.healthchecker: DEBUG